version: '3'

services:
  server:
    # Путь до Dockerfile
    build: ./backend
    # Имя для создаваемого контейнера
    container_name: backend-flask
    # Создание переменных окружения в контейнере
    environment:
      # для отладки (при запуске в релиз убрать!)
      - FLASK_ENV=development
      # Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True
      # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./backend:/backend
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5000:5000"
    command: gunicorn main:"create_flask_app()" -b 0.0.0.0:5000 --reload
  # dashboard:
  #   image: master-image
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #   command: rq-dashboard --port 5555 --redis-url redis://redis:6379/0

  # redis:
  #   image: redis
